---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hybrid-workload

resources:
  - resources/namespace.yaml
  - resources/galera-vm-01.yaml
  - resources/galera-vm-02.yaml
  - resources/imagestream.yaml
  - resources/buildconfig.yaml
  - resources/service.yaml
  - resources/deployment.yaml
  - resources/secret.yaml
  - resources/route.yaml
  - resources/service-knative.yaml
  - resources/networkpolicy.yaml
