apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: team1
users:
  - user1
  - user2
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: team2
users:
  - user3
  - user4
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-admin-group
  namespace: dev
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: team1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-admin-group
  namespace: dev
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: team2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
