---
# db_user = userOSR
# db_password = WmyArnyFmiyKrt7n
# db = sampledb
kind: Secret
apiVersion: v1
metadata:
  name: mysql
data:
  database-name: c2FtcGxlZGI=
  database-password: V215QXJueUZtaXlLcnQ3bg==
  database-root-password: a0xqZkJkaUpjb2NkNGY1WA==
  database-user: dXNlck9TUg==
type: Opaque
