---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: stress-test-cronjob
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      completions: 10
      parallelism: 10
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: stress
            image: image-registry.openshift-image-registry.svc:5000/stress-job/stress-job:1.0
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "500m"
                memory: "500Mi"
              limits:
                cpu: "500m"
                memory: "500Mi"
