---
apiVersion: batch/v1
kind: Job
metadata:
  name: stress-job
spec:
  completions: 40
  parallelism: 40
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: stress
        image: image-registry.openshift-image-registry.svc:5000/stress-job/stress-job:1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "6Gi"
          limits:
            cpu: "2"
            memory: "6Gi"
