---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/namespace.yaml
  - resources/secret.yaml
  - resources/multiclusterobservability.yaml

secretGenerator:
  - name: multiclusterhub-operator-pull-secret
    namespace: open-cluster-management-observability
    type: Opaque
    behavior: replace
    files:
      - .dockerconfigjson=assets-temporary/pull-secret.txt

generatorOptions:
  disableNameSuffixHash: true
