apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: my_htpasswd_provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd-secret
  - name: githubidp
    mappingMethod: claim
    type: GitHub
    github:
      clientID: <CLIENT_ID>
      clientSecret:
        name: github-oauth
      organizations:
      - <ORGANIZATION>
