---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: stress-job
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
  source:
    type: Git
    git:
      uri: "https://github.com/Caseraw/OpenShiftDemoTime.git"
      ref: "UC17-cluster-autoscaler"
    contextDir: scenarios/uc17-cluster-autoscaler/stress-test
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: stress-job:1.0
