---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend-pod-spot-build
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
  source:
    type: Git
    git:
      uri: "https://github.com/Caseraw/OpenShiftDemoTime.git"
      ref: main
    contextDir: scenarios/uc22-cluster-upgrade/backend-pod-spot
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.11-ubi9
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: backend-pod-spot:1.0
