apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: podinfo-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: podinfo-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: podinfo
        server: "{{server}}"
      project: default
      sources:
        - path: scenarios/uc16-workload-scalability/podinfo
          repoURL: https://github.com/Caseraw/OpenShiftDemoTime.git
          targetRevision: UC16--Workload-scalability
          repositoryType: git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: podinfo-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: provider
              operator: In
              values:
                - dc