---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management

resources:
  - resources/secret.yaml

secretGenerator:
  - name: aws
    type: Opaque
    behavior: replace
    files:
      - pullSecret=assets-temporary/pull-secret.txt
      - ssh-privatekey=assets-temporary/id_rsa
      - ssh-publickey=assets-temporary/id_rsa.pub
    envs:
      - assets-temporary/bundle.env

generatorOptions:
  disableNameSuffixHash: true
