kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: scaling-hpa
  namespace: scaling
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10   # default is 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scaling
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50