---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: podinfo-rules
  namespace: podinfo
  labels:
    app: podinfo
spec:
  groups:
    - name: podinfo.availability
      rules:
        - alert: PodinfoDown
          expr: max_over_time(up{namespace="podinfo",service="podinfo"}[2m]) == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "podinfo is down"
            description: "No healthy targets for Service podinfo in namespace podinfo for 5m."

    - name: podinfo.performance
      rules:
        - alert: PodinfoHighCPU
          expr: rate(process_cpu_seconds_total{namespace="podinfo",service="podinfo"}[5m]) > 0.5
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage in podinfo"
            description: "CPU > 0.5 cores for 10m."

        - alert: PodinfoHighRSS
          expr: process_resident_memory_bytes{namespace="podinfo",service="podinfo"} > 300 * 1024 * 1024
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage in podinfo"
            description: "RSS memory > 300Mi for 10m."

        - alert: PodinfoNoRequests
          expr: increase(http_requests_total{namespace="podinfo",service="podinfo"}[15m]) == 0
          for: 30m
          labels:
            severity: info
          annotations:
            summary: "No incoming requests"
            description: "No HTTP requests observed for 30m."
