---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  namespaceSelector:
    matchNames: ["podinfo"]
  selector:
    matchLabels:
      app: podinfo
  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
