kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: demo-dockerfile
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'demo-dockerfile:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/Caseraw/OpenShiftDemoTime'
      ref: UC04--Container-as-a-service
    contextDir: /scenarios/uc04-container-as-a-service/dockerfile
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial