apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- patch: |-
    - op: replace
      path: /spec/source/contextDir
      value: /scenarios/uc04-container-as-a-service/jar
  target:
    kind: BuildConfig