---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: stackrox
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: stackrox-init-bundle-placement
  namespace: stackrox
spec:
  clusterSets:
    - default
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values: ["dev"]
            - key: local-cluster
              operator: NotIn
              values: ["true"]
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: stackrox-init-bundle-binding
  namespace: stackrox
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: stackrox-init-bundle-placement
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: stackrox-init-bundle-secrets
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: stackrox-init-bundle-secrets
  namespace: stackrox
  annotations:
    policy.open-cluster-management.io/description: Distribute RHACS init-bundle to spokes
spec:
  disabled: false
  policy-templates:
    # 1) Ensure target namespace exists on spokes
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: stackrox-namespace
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: stackrox
    # 2) Render/apply the three Secrets from the hub Secret's data.bundle.yaml
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: stackrox-init-bundle
        spec:
          remediationAction: enforce
          pruneObjectBehavior: DeleteIfCreated
          severity: low
          object-templates-raw: |
            {{hub -}}
            {{- $raw := fromSecret "stackrox" "rox-init-bundle" "bundle.yaml" | base64dec -}}
            {{- range (splitList "\n---\n" $raw) }}
            {{- $doc := trim . -}}
            {{- if $doc }}
            - complianceType: musthave
              objectDefinition:
    {{ $doc | indent 12 }}
            {{- end }}
            {{- end }}
            {{- hub}}