---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: rhacm-gitops-cluster
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    name: rhacm-gitops-cluster-placement
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
