---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-pipelines-hub
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-pipelines-hub-placement
        requeueAfterSeconds: 10
  template:
    metadata:
      name: demo-pipelines-hub-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      destination:
        namespace: demo-pipelines
        server: "{{server}}"
      project: default
      sources:
        - path: scenarios/uc17-cluster-autoscaler/kustomize/base/demo-pipelines-hub
          repoURL: https://github.com/Caseraw/OpenShiftDemoTime.git
          targetRevision: UC17-cluster-autoscaler
          repositoryType: git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
