---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: podspot-backend-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - dev
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: podspot-frontend-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: In
              values:
                - "true"
