---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-hyrbrid-workload
  namespace: demo-pipelines
spec:
  finally:
    - name: openshift-client-final
      params:
        - name: SCRIPT
          value: |-
            ROUTE="https://$(oc get route openshift-gitops-server -n openshift-gitops -o jsonpath='{.spec.host}')"

            echo "ArgoCD Application for Hybrid Workload has been created"
            echo "To view the Application go to: $ROUTE/applications/openshift-gitops/hybrid-workload"
        - name: VERSION
          value: '4.19'
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/Caseraw/OpenShiftDemoTime.git'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'ghcr.io/tektoncd-catalog/git-clone:v1.1.0'
        - name: userHome
          value: /home/git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: openshift-client
      params:
        - name: SCRIPT
          value: |-
            pwd
            ls -la
            ls -la /workspace/output

            oc apply -k scenarios/demo-rhacm-hybrid-workload/argocd-applications/hybrid-workload
        - name: VERSION
          value: '4.19'
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: workspace
  workspaces:
    - name: workspace
