apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: php-mysql-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: php-app
  pollingInterval: 15   # seconds
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: mysql
      metadata:
        connectionString: "Server=mysql;Database=keda_php;User=demo;Password=demo;"
        query: "SELECT count FROM request_counter WHERE id=1"
        targetValue: "10"   # scale when counter >= 50
