---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: <INSERT NODE NAME>
  containers:
    - name: oc-cli
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      command: ["sleep", "infinity"]
      tty: true
      stdin: true
  restartPolicy: Always
