---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backend-build
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/Caseraw/OpenShiftDemoTime.git"
    contextDir: scenarios/uc22-cluster-upgrade/backend
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-311:latest
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
