kind: NamespaceConfig
apiVersion: redhatcop.redhat.io/v1alpha1
metadata:
  name: tenant-namespaceconfig
spec:
  labelSelector:
    matchLabels:
      type: tenant
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: standard-tenant
          namespace: {{ .Name }}
        spec:
          hard:
            pods: "4" 
            requests.cpu: "1" 
            requests.memory: 1Gi 
            requests.ephemeral-storage: 2Gi 
            limits.cpu: "2" 
            limits.memory: 2Gi 
            limits.ephemeral-storage: 4Gi
    - objectTemplate: |
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: deny-other-namespaces
          namespace: {{ .Name }}
        spec:
          podSelector: {}
          ingress:
            - from:
                - podSelector: {}