apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: myapp-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: myapp-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      sources:
        - repositoryType: git
          repoURL: https://github.com/Caseraw/OpenShiftDemoTime
          targetRevision: main
          path: scenarios/uc26-cluster-and-site-resiliency
      destination:
        namespace: uc26
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: myapp-placement
  namespace: openshift-gitops
spec:
  numberOfClusters: 3
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: site
              operator: In
              values:
                - aws
                - dc