---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mini-contacts-frontend
  labels: { app: api }
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"mini-contacts-api:latest"},
        "fieldPath":"spec.template.spec.containers[?(@.name==\"api\")].image"}]
spec:
  replicas: 2
  selector:
    matchLabels: { app: api }
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: "" # populated by trigger
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef: { name: secret-db-api }
            - configMapRef: { name: api-config }
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits:   { cpu: "1",  memory: 512Mi }
